import type { BlackjackConfig, CrashConfig, DiceConfig, RouletteConfig, TableGameConfig, TreasureDigConfig } from "./types";

const demoOnlyCopy =
  "Demo table game using virtual coins only. No cash value, deposits, withdrawals, prizes, or redemptions.";

export const blackjackConfig: BlackjackConfig = {
  id: "blackjack",
  name: "Blackjack",
  theme: "Green felt cards",
  minBet: 1,
  maxBet: 500,
  minBetGold: 1,
  maxBetGold: 500,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: 5000,
  houseEdgeTarget: 0.018,
  currency: "GOLD",
  demoOnlyCopy,
  rules: ["Dealer hits soft 17", "Blackjack pays 3:2", "8-deck shoe", "Same-value splits and resplits up to 8 hands"],
  dealerHitsSoft17: true,
  blackjackPayout: 1.5,
  allowDouble: true,
  allowSplit: true,
  allowInsurance: true,
  allowEvenMoney: true,
  allowResplit: true,
  allowSplitTens: true,
  allowDoubleAfterSplit: true,
  deckCount: 8,
  shoeReshuffleThreshold: 60,
  maxHandsAfterSplit: 8,
  maxSplitHands: 8,
  // Demo tuning only. Real-money games need certified RNG, math, legal, and responsible gaming review.
  dealerAdvantageAssistRate: 0.04,
};

export const rouletteConfig: RouletteConfig = {
  id: "roulette",
  name: "Roulette",
  theme: "American double-zero wheel",
  minBet: 0.1,
  maxBet: 5000,
  minBetGold: 10,
  maxBetGold: 5000,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 250,
  maxPayout: 50000,
  houseEdgeTarget: 0.0526,
  currency: "GOLD",
  demoOnlyCopy,
  rules: ["American roulette with 0 and 00", "Outside bets pay 1:1", "Inside bets include straight, split, street, corner, and six-line"],
  payouts: {
    color: 1,
    parity: 1,
    range: 1,
    dozen: 2,
    column: 2,
    straight: 35,
    split: 17,
    street: 11,
    corner: 8,
    sixLine: 5,
    basket: 6,
  },
  maxTotalBetGold: 5000,
  maxPayoutGold: 50000,
  realMoneyMinCentsPlaceholder: 1,
};

export const diceConfig: DiceConfig = {
  id: "dice",
  name: "Over/Under",
  theme: "Higher or lower table",
  minBet: 10,
  maxBet: 500,
  minBetGold: 10,
  maxBetGold: 500,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: 12000,
  houseEdgeTarget: 0.03,
  currency: "GOLD",
  demoOnlyCopy,
  rules: ["Pick over or under the target", "Payout is based on probability minus a configurable demo house edge"],
  edge: 0.03,
  minTarget: 2,
  maxTarget: 98,
};

export const crashConfig: CrashConfig = {
  id: "crash",
  name: "Crash",
  theme: "Rising multiplier race",
  minBet: 10,
  maxBet: 500,
  minBetGold: 10,
  maxBetGold: 500,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: 25000,
  houseEdgeTarget: 0.04,
  currency: "GOLD",
  demoOnlyCopy,
  rules: ["Multiplier rises from 1.00x", "Cash out before the crash to win", "Crash point uses a demo exponential distribution with house edge"],
  edge: 0.04,
  minCrashPoint: 1,
  maxCrashPoint: 100,
};

export const treasureDigConfig: TreasureDigConfig = {
  id: "treasureDig",
  name: "Treasure Dig",
  theme: "Multiplier mine grid",
  minBet: 1,
  maxBet: 10000,
  minBetGold: 1,
  maxBetGold: 10000,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 10000,
  maxPayout: 9000000000000000,
  houseEdgeTarget: 0.15,
  currency: "GOLD",
  demoOnlyCopy,
  rules: ["Pick safe treasure tiles on a 5x5 grid", "Cash out before uncovering a trap", "Multiplier gems can boost the total cash out"],
  gridSize: 5,
  minTraps: 1,
  maxTraps: 24,
  edge: 0.15,
  minMultiplierTiles: 0,
  maxMultiplierTiles: 2,
  multiplierValues: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 5, 5, 10, 25, 50],
};

export const tableGameConfigs: TableGameConfig[] = [blackjackConfig, rouletteConfig, diceConfig, crashConfig, treasureDigConfig];
