import type { BlackjackConfig, CrashConfig, DiceConfig, RouletteConfig, TableGameConfig, TreasureDigConfig } from "./types";
import { brickBreakBonusConfig } from "./brickBreakBonusEngine";
import { balloonPopConfig } from "./balloonPopEngine";
import { lavaRunConfig } from "./lavaRunEngine";
import { emberStackConfig } from "./emberStackEngine";
import { COMPLIANCE_COPY } from "../lib/compliance";
import { DEMO_MAX_PAYOUT, DEMO_MAX_SINGLE_BET, DEMO_MAX_TOTAL_BET } from "../economy/limits";

const demoOnlyCopy = COMPLIANCE_COPY;

const tableGameArtwork = {
  blackjack: new URL("../assets/branding/game-logos/blackjack_logo.png", import.meta.url).href,
  roulette: new URL("../assets/branding/game-logos/roulette_logo.png", import.meta.url).href,
  dice: new URL("../assets/branding/game-logos/over_under_logo.png", import.meta.url).href,
  crash: new URL("../assets/branding/game-logos/crash_logo.png", import.meta.url).href,
  treasureDig: new URL("../assets/branding/game-logos/treasure_dig_logo.png", import.meta.url).href,
  brickBreakBonus: new URL("../assets/branding/game-logos/brickbreak_logo.png", import.meta.url).href,
  balloonPop: new URL("../assets/branding/game-logos/balloon_pop_logo.png", import.meta.url).href,
  lavaRun: new URL("../assets/branding/game-logos/lava_run_logo.png", import.meta.url).href,
  emberStack: new URL("../assets/branding/game-logos/ember_stack_logo.png", import.meta.url).href,
} as const;

export const blackjackConfig: BlackjackConfig = {
  id: "blackjack",
  name: "Blackjack",
  theme: "Green felt cards",
  minBet: 0.01,
  maxBet: 1000000,
  minBetGold: 1,
  maxBetGold: 1000000,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  minBetSweepstakes: 0.01,
  maxBetSweepstakes: 200,
  maxPayout: DEMO_MAX_PAYOUT,
  houseEdgeTarget: 0.07,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.blackjack,
  rules: ["Dealer hits soft 17", "Blackjack pays 3:2", "8-deck shoe", "Same-value splits and resplits up to 8 hands"],
  dealerHitsSoft17: true,
  blackjackPayout: 1.5,
  allowDouble: true,
  allowSplit: true,
  allowInsurance: true,
  allowEvenMoney: true,
  allowResplit: true,
  allowSplitTens: true,
  allowDoubleAfterSplit: true,
  deckCount: 8,
  shoeReshuffleThreshold: 60,
  maxHandsAfterSplit: 8,
  maxSplitHands: 8,
  // Demo tuning only. Real-money games need certified RNG, math, legal, and responsible gaming review.
  dealerAdvantageAssistRate: 0.04,
};

export const rouletteConfig: RouletteConfig = {
  id: "roulette",
  name: "Roulette",
  theme: "American double-zero wheel",
  minBet: 0.01,
  maxBet: 1000000,
  minBetGold: 1,
  maxBetGold: 1000000,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: DEMO_MAX_PAYOUT,
  houseEdgeTarget: 0.0526,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.roulette,
  rules: ["American roulette with 0 and 00", "Outside bets pay 1:1", "Inside bets include straight, split, street, corner, and six-line"],
  payouts: {
    color: 1,
    parity: 1,
    range: 1,
    dozen: 2,
    column: 2,
    straight: 35,
    split: 17,
    street: 11,
    corner: 8,
    sixLine: 5,
    basket: 6,
  },
  maxTotalBetGold: 1000000,
  maxPayoutGold: DEMO_MAX_PAYOUT,
  realMoneyMinCentsPlaceholder: 1,
};

export const diceConfig: DiceConfig = {
  id: "dice",
  name: "Over/Under",
  theme: "Higher or lower table",
  minBet: 10,
  maxBet: DEMO_MAX_SINGLE_BET,
  minBetGold: 10,
  maxBetGold: 500,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: 12000,
  houseEdgeTarget: 0.07,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.dice,
  rules: ["Pick over or under the target", "Payout is based on probability minus a configurable demo house edge"],
  edge: 0.07,
  minTarget: 2,
  maxTarget: 98,
};

export const crashConfig: CrashConfig = {
  id: "crash",
  name: "Crash",
  theme: "Rising multiplier race",
  minBet: 10,
  maxBet: DEMO_MAX_SINGLE_BET,
  minBetGold: 10,
  maxBetGold: 500,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: 25000,
  houseEdgeTarget: 0.06,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.crash,
  rules: ["Multiplier rises from 1.00x", "Collect before the crash to win virtual coins", "Crash point uses a demo exponential distribution with house edge"],
  edge: 0.06,
  minCrashPoint: 1,
  maxCrashPoint: 100,
};

export const treasureDigConfig: TreasureDigConfig = {
  id: "treasureDig",
  name: "Treasure Dig",
  theme: "Multiplier mine grid",
  minBet: 20,
  maxBet: DEMO_MAX_SINGLE_BET,
  minBetGold: 20,
  maxBetGold: DEMO_MAX_SINGLE_BET,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: DEMO_MAX_SINGLE_BET,
  maxPayout: DEMO_MAX_PAYOUT,
  houseEdgeTarget: 0.08,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.treasureDig,
  rules: ["Pick safe treasure tiles on a 5x5 grid", "Collect before uncovering a trap", "Multiplier gems can boost the collected virtual coins"],
  gridSize: 5,
  minTraps: 1,
  maxTraps: 24,
  edge: 0.08,
  minMultiplierTiles: 0,
  maxMultiplierTiles: 2,
  multiplierValues: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 5, 5, 10, 25, 50],
};

export const brickBreakBonusTableConfig: TableGameConfig = {
  id: "brickBreakBonus",
  name: brickBreakBonusConfig.name,
  theme: brickBreakBonusConfig.theme,
  minBet: brickBreakBonusConfig.minBet,
  maxBet: brickBreakBonusConfig.maxBet,
  minBetGold: brickBreakBonusConfig.minBet,
  maxBetGold: brickBreakBonusConfig.maxBet,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: brickBreakBonusConfig.maxPayout,
  houseEdgeTarget: 1 - brickBreakBonusConfig.targetRtp,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.brickBreakBonus,
  rules: ["Place a wager and press Play", "CPU autoplay controls the paddle and ball", "RNG result is generated before animation starts"],
};

export const balloonPopTableConfig: TableGameConfig = {
  id: "balloonPop",
  name: balloonPopConfig.name,
  theme: balloonPopConfig.theme,
  minBet: balloonPopConfig.minBet,
  maxBet: balloonPopConfig.maxBet,
  minBetGold: balloonPopConfig.minBet,
  maxBetGold: balloonPopConfig.maxBet,
  minBetRealCentsPlaceholder: 1,
  maxBetRealCentsPlaceholder: 500,
  maxPayout: balloonPopConfig.maxBet * balloonPopConfig.maxWinMultiplier,
  houseEdgeTarget: 1 - balloonPopConfig.targetRtp,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.balloonPop,
  rules: ["Choose 3 balloons", "Prize map is generated before darts are thrown", "Multipliers apply to current round winnings"],
};

export const lavaRunTableConfig: TableGameConfig = {
  id: "lavaRun",
  name: lavaRunConfig.name,
  theme: lavaRunConfig.theme,
  minBet: lavaRunConfig.minBet,
  maxBet: lavaRunConfig.maxBet,
  minBetGold: lavaRunConfig.minBetGold,
  maxBetGold: lavaRunConfig.maxBetGold,
  minBetRealCentsPlaceholder: lavaRunConfig.minBetRealCentsPlaceholder,
  maxBetRealCentsPlaceholder: lavaRunConfig.maxBetRealCentsPlaceholder,
  maxPayout: lavaRunConfig.maxPayout,
  houseEdgeTarget: 1 - lavaRunConfig.targetRtp,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.lavaRun,
  rules: ["Choose Low, Medium, or High risk", "Pick lava platforms one row at a time", "Cash out after safe steps or risk the next reveal"],
};

export const emberStackTableConfig: TableGameConfig = {
  id: "emberStack",
  name: emberStackConfig.name,
  theme: emberStackConfig.theme,
  minBet: emberStackConfig.minBet,
  maxBet: emberStackConfig.maxBet,
  minBetGold: emberStackConfig.minBetGold,
  maxBetGold: emberStackConfig.maxBetGold,
  minBetRealCentsPlaceholder: emberStackConfig.minBetRealCentsPlaceholder,
  maxBetRealCentsPlaceholder: emberStackConfig.maxBetRealCentsPlaceholder,
  maxPayout: emberStackConfig.maxPayout,
  houseEdgeTarget: 1 - emberStackConfig.targetRtp,
  currency: "GOLD",
  demoOnlyCopy,
  artwork: tableGameArtwork.emberStack,
  rules: ["Start a CPU-run stack attempt", "Perfect, good, and thin stacks raise the multiplier", "Cash out after a success or continue the run"],
};

export const tableGameConfigs: TableGameConfig[] = [emberStackTableConfig, lavaRunTableConfig, balloonPopTableConfig, brickBreakBonusTableConfig, blackjackConfig, rouletteConfig, diceConfig, crashConfig, treasureDigConfig];
