export const frontierUiAssets = {
  sheet: "/assets/ui/frontier-ui-sheet.png",
  titleLogo: "/assets/ui/frontier/title-logo.png",
  backgroundMobile: "/assets/ui/frontier/background-mobile.png",
  reelFrame: "/assets/ui/frontier/reel-frame.png",
  jackpotGrand: "/assets/ui/frontier/jackpot-grand.png",
  jackpotMajor: "/assets/ui/frontier/jackpot-major.png",
  jackpotMinor: "/assets/ui/frontier/jackpot-minor.png",
  jackpotMini: "/assets/ui/frontier/jackpot-mini.png",
  spinButton: "/assets/ui/frontier/spin-button.png",
  spinButtonPressed: "/assets/ui/frontier/spin-button-pressed.png",
  buyBonusButton: "/assets/ui/frontier/buy-bonus-button.png",
  respinButton: "/assets/ui/frontier/respin-button.png",
  balancePanel: "/assets/ui/frontier/balance-panel.png",
  betPanel: "/assets/ui/frontier/bet-panel.png",
  quickBet10: "/assets/ui/frontier/quick-bet-10.png",
  quickBet20: "/assets/ui/frontier/quick-bet-20.png",
  quickBet50: "/assets/ui/frontier/quick-bet-50.png",
  quickBet100: "/assets/ui/frontier/quick-bet-100.png",
  quickBet250: "/assets/ui/frontier/quick-bet-250.png",
  holdAndWinBanner: "/assets/ui/frontier/hold-and-win-banner.png",
  respinsPanel: "/assets/ui/frontier/respins-panel.png",
  bonusTotalPanel: "/assets/ui/frontier/bonus-total-panel.png",
  winBig: "/assets/ui/frontier/win-big.png",
  winMega: "/assets/ui/frontier/win-mega.png",
  winEpic: "/assets/ui/frontier/win-epic.png",
  iconMenu: "/assets/ui/frontier/icon-menu.png",
  iconInfo: "/assets/ui/frontier/icon-info.png",
  iconSound: "/assets/ui/frontier/icon-sound.png",
  iconSettings: "/assets/ui/frontier/icon-settings.png",
} as const;

export const requiredFrontierUiAssetKeys = Object.keys(frontierUiAssets) as Array<keyof typeof frontierUiAssets>;
