import { standardPaylines } from "./paylines";
import type { SlotConfig } from "./types";

const featureSymbols = {
  wild: { id: "wild", label: "WILD", icon: "âœ¦", weight: 3, kind: "wild" as const, color: "#67e8f9" },
  scatter: { id: "scatter", label: "SCATTER", icon: "â—†", weight: 3, kind: "scatter" as const, color: "#c084fc" },
  bonus: { id: "bonus", label: "BONUS", icon: "â˜…", weight: 3, kind: "bonus" as const, color: "#f0abfc" },
};

export const slotConfigs: SlotConfig[] = [
  {
    id: "frontier-fortune",
    name: "Frontier Fortune",
    theme: "Desert relics and canyon spirits",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 0.1,
    maxBet: 100000,
    volatility: "High",
    targetRtp: 0.91,
    maxPayoutMultiplier: 1000,
    currencyBetOptions: {
      GOLD: [10, 50, 100, 250, 500, 1000, 10000, 20000, 50000, 100000],
      BONUS: [0.1, 0.2, 0.4, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 3, 5, 10],
    },
    jackpotLabels: { Grand: "1000x", Major: "50x", Minor: "10x", Mini: "5x" },
    buyBonus: { enabled: true, costMultiplier: 100, featureType: "HOLD_AND_WIN" },
    bonusBuys: [
      {
        id: "hold-and-win",
        label: "Hold & Win",
        featureType: "HOLD_AND_WIN",
        costMultiplier: 100,
        currencyCostMultipliers: { GOLD: 100, BONUS: 100 },
        payoutBetMultipliers: { GOLD: 19, BONUS: 19 },
        startingCoins: 6,
      },
      {
        id: "wheel-bonus",
        label: "Wheel Bonus",
        featureType: "WHEEL_BONUS",
        costMultiplier: 80,
        currencyCostMultipliers: { GOLD: 80, BONUS: 80 },
        payoutBetMultipliers: { GOLD: 1, BONUS: 1 },
        startingCoins: 0,
      },
    ],
    boostSpins: {
      GOLD_BOOST: { label: "Gold Boost", costMultiplier: 1.52, coinWeightMultiplier: 1.55, holdAndWinTriggerBoost: 1.2, collectorTriggerBoost: 5 },
      SCATTER_BOOST: { label: "Scatter Boost", costMultiplier: 1.44, scatterWeightMultiplier: 2.5, wheelTriggerBoost: 1.25 },
    },
    holdAndWin: {
      coinValueMultipliers: [0.1, 0.25, 0.5, 1, 1.5, 2, 2.5, 3, 5, 10, 50],
      coinAwards: [
        { label: "0.1x", multiplier: 0.1, weight: 38 },
        { label: "0.25x", multiplier: 0.25, weight: 28 },
        { label: "0.5x", multiplier: 0.5, weight: 18 },
        { label: "1x", multiplier: 1, weight: 9 },
        { label: "1.5x", multiplier: 1.5, weight: 4 },
        { label: "2x", multiplier: 2, weight: 2.2 },
        { label: "2.5x", multiplier: 2.5, weight: 1.2 },
        { label: "3x", multiplier: 3, weight: 0.7 },
        { label: "Mini", multiplier: 5, weight: 0.22, jackpotLabel: "Mini" },
        { label: "Minor", multiplier: 10, weight: 0.08, jackpotLabel: "Minor" },
        { label: "Major", multiplier: 50, weight: 0.012, jackpotLabel: "Major" },
      ],
      grandMultiplier: 1000,
      majorMultiplier: 50,
      minorMultiplier: 10,
      miniMultiplier: 5,
      coinLandingChance: 0.072,
      triggerCount: 6,
    },
    wheelBonus: {
      triggerCount: 3,
      segments: [
        { label: "2x", multiplier: 2, weight: 22 },
        { label: "10 Free Spins", multiplier: 0, weight: 10, freeSpinsAwarded: 10 },
        { label: "5x", multiplier: 5, weight: 22 },
        { label: "Mini x2", multiplier: 10, weight: 5, jackpotLabel: "Mini" },
        { label: "Hold & Win", multiplier: 0, weight: 24, featureTrigger: "HOLD_AND_WIN" },
        { label: "10x", multiplier: 10, weight: 7 },
        { label: "15 Free Spins", multiplier: 0, weight: 3, freeSpinsAwarded: 15 },
        { label: "Minor x2", multiplier: 20, weight: 2, jackpotLabel: "Minor" },
        { label: "Super Hold & Win", multiplier: 0, weight: 4, featureTrigger: "SUPER_HOLD_AND_WIN" },
        { label: "15x", multiplier: 15, weight: 3 },
        { label: "20 Free Spins", multiplier: 0, weight: 0.5, freeSpinsAwarded: 20 },
        { label: "Major x2", multiplier: 100, weight: 0.2, jackpotLabel: "Major" },
      ],
    },
    coinCollector: { enabled: true, maxCoins: 5, minCollect: 1, maxCollect: 5, triggerChancePerCoin: 0.008, resetOnTrigger: true },
    featureTypes: ["HOLD_AND_WIN", "WHEEL_BONUS"],
    specialSymbols: { wild: "mirage_wild", scatter: "oasis_scatter", bonus: "coin_100", coin: "coin_100", collector: "sun_hawk" },
    symbols: [
      { id: "sun_hawk", label: "Sun Hawk", icon: "H", image: "/assets/symbols/frontier/sun_hawk.png", weight: 9.1, color: "#facc15" },
      { id: "canyon_ram", label: "Canyon Ram", icon: "R", image: "/assets/symbols/frontier/canyon_ram.png", weight: 10.4, color: "#fb923c" },
      { id: "sand_fox", label: "Sand Fox", icon: "F", image: "/assets/symbols/frontier/sand_fox.png", weight: 13, color: "#f97316" },
      { id: "crystal_scorpion", label: "Crystal Scorpion", icon: "S", image: "/assets/symbols/frontier/crystal_scorpion.png", weight: 14.3, color: "#a78bfa" },
      { id: "desert_relic", label: "Desert Relic", icon: "D", image: "/assets/symbols/frontier/desert_relic.png", weight: 16.9, color: "#facc15" },
      { id: "oasis_gem", label: "Oasis Gem", icon: "G", image: "/assets/symbols/frontier/oasis_gem.png", weight: 19.5, color: "#22d3ee" },
      { id: "dust_spirit", label: "Dust Spirit", icon: "P", image: "/assets/symbols/frontier/dust_spirit.png", weight: 22.1, color: "#93c5fd" },
      { id: "mirage_wild", label: "Mirage Wild", icon: "W", image: "/assets/symbols/frontier/mirage_wild.png", weight: 4, kind: "wild", color: "#f0abfc" },
      { id: "oasis_scatter", label: "Oasis Scatter", icon: "O", image: "/assets/symbols/frontier/oasis_scatter.png", weight: 2.2, kind: "scatter", color: "#34d399" },
      { id: "coin_100", label: "Gold Coin 0.1x-1x", icon: "0.1x", image: "/assets/symbols/frontier/coin_100.png", weight: 4.6, kind: "coin", color: "#fde047" },
      { id: "coin_250", label: "Gold Coin 1.5x-2x", icon: "1.5x", image: "/assets/symbols/frontier/coin_250.png", weight: 0, kind: "coin", color: "#fde047" },
      { id: "coin_500", label: "Gold Coin 2.5x-3x", icon: "2.5x", image: "/assets/symbols/frontier/coin_500.png", weight: 0, kind: "coin", color: "#fde047" },
      { id: "coin_1000", label: "Jackpot Coin Mini/Minor/Major", icon: "JP", image: "/assets/symbols/frontier/coin_1000.png", weight: 0, kind: "coin", color: "#fde047" },
      { id: "A", label: "A", icon: "A", image: "/assets/symbols/frontier/A.png", weight: 19, color: "#ef4444" },
      { id: "K", label: "K", icon: "K", image: "/assets/symbols/frontier/K.png", weight: 20, color: "#a855f7" },
      { id: "Q", label: "Q", icon: "Q", image: "/assets/symbols/frontier/Q.png", weight: 21, color: "#0ea5e9" },
      { id: "J", label: "J", icon: "J", image: "/assets/symbols/frontier/J.png", weight: 22, color: "#22c55e" },
      { id: "10", label: "10", icon: "10", image: "/assets/symbols/frontier/10.png", weight: 23, color: "#f59e0b" },
    ],
    waysToWin: "8 canyon paylines",
    payoutTable: [
      { symbol: "sun_hawk", count: 5, multiplier: 16182 },
      { symbol: "sun_hawk", count: 4, multiplier: 2337.4 },
      { symbol: "sun_hawk", count: 3, multiplier: 80.91 },
      { symbol: "canyon_ram", count: 5, multiplier: 12945.6 },
      { symbol: "canyon_ram", count: 4, multiplier: 1887.9 },
      { symbol: "canyon_ram", count: 3, multiplier: 68.32 },
      { symbol: "sand_fox", count: 5, multiplier: 10068.8 },
      { symbol: "sand_fox", count: 4, multiplier: 1294.56 },
      { symbol: "sand_fox", count: 3, multiplier: 44.95 },
      { symbol: "crystal_scorpion", count: 5, multiplier: 8450.6 },
      { symbol: "crystal_scorpion", count: 4, multiplier: 1078.8 },
      { symbol: "crystal_scorpion", count: 3, multiplier: 35.96 },
      { symbol: "desert_relic", count: 5, multiplier: 6472.8 },
      { symbol: "desert_relic", count: 4, multiplier: 845.06 },
      { symbol: "desert_relic", count: 3, multiplier: 26.97 },
      { symbol: "oasis_gem", count: 5, multiplier: 4674.8 },
      { symbol: "oasis_gem", count: 4, multiplier: 611.32 },
      { symbol: "oasis_gem", count: 3, multiplier: 17.98 },
      { symbol: "dust_spirit", count: 5, multiplier: 3596 },
      { symbol: "dust_spirit", count: 4, multiplier: 467.48 },
      { symbol: "dust_spirit", count: 3, multiplier: 14.38 },
      { symbol: "A", count: 5, multiplier: 1528.3 },
      { symbol: "A", count: 4, multiplier: 152.83 },
      { symbol: "A", count: 3, multiplier: 1.6 },
      { symbol: "K", count: 5, multiplier: 1294.56 },
      { symbol: "K", count: 4, multiplier: 125.86 },
      { symbol: "K", count: 3, multiplier: 1.3 },
      { symbol: "Q", count: 5, multiplier: 1078.8 },
      { symbol: "Q", count: 4, multiplier: 104.68 },
      { symbol: "Q", count: 3, multiplier: 1.1 },
      { symbol: "J", count: 5, multiplier: 827.08 },
      { symbol: "J", count: 4, multiplier: 79.11 },
      { symbol: "J", count: 3, multiplier: 0.9 },
      { symbol: "10", count: 5, multiplier: 683.24 },
      { symbol: "10", count: 4, multiplier: 64.73 },
      { symbol: "10", count: 3, multiplier: 0.8 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "oasis_scatter",
    bonusSymbol: "coin_100",
    bonusFeature: { meterPerSpin: 9 },
    freeSpins: { triggerCount: 99, awarded: [0, 0], winMultiplier: 1, retrigger: true, retriggerAward: 5, maxSpins: 30, stickyWilds: true },
    pickBonus: { triggerCount: 99, picks: 0, awards: [] },
    demoProgressive: { seed: 150000, contributionRate: 0.006, maxPayoutMultiplier: 120 },
    visual: {
      accent: "#38bdf8",
      secondary: "#f97316",
      panel: "#32160d",
      logo: "FF",
      logoImage: "/assets/ui/frontier/title-logo.png",
      background: "frontier",
      cabinet: "canyon",
    },
  },
  {
    id: "frontier-fortune-legacy",
    name: "Frontier Fortune Legacy",
    theme: "Desert relics and canyon spirits",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 500,
    volatility: "High",
    targetRtp: 0.91,
    maxPayoutMultiplier: 70,
    jackpotLabels: { Grand: "1000x", Major: "100x", Minor: "25x", Mini: "10x" },
    buyBonus: { enabled: true, costMultiplier: 80, featureType: "HOLD_AND_WIN" },
    featureTypes: ["HOLD_AND_WIN"],
    specialSymbols: { wild: "mirage_wild", scatter: "oasis_scatter", bonus: "coin_100", coin: "coin_100", collector: "sun_hawk" },
    symbols: [
      { id: "bison", label: "Buffalo", icon: "ðŸƒ", weight: 8, color: "#f97316" },
      { id: "eagle", label: "Eagle", icon: "ðŸ¦…", weight: 8, color: "#93c5fd" },
      { id: "wolf", label: "Wolf", icon: "ðŸº", weight: 12, color: "#a78bfa" },
      { id: "cougar", label: "Cougar", icon: "ðŸ¾", weight: 14, color: "#22d3ee" },
      { id: "canyon", label: "Canyon", icon: "ðŸœï¸", weight: 20, color: "#fb7185" },
      { id: "wild", label: "Wild", icon: "WILD", weight: 4, kind: "wild", color: "#f0abfc" },
      { id: "scatter", label: "Scatter", icon: "ðŸŒµ", weight: 3, kind: "scatter", color: "#34d399" },
      { id: "bonus", label: "Bonus", icon: "â­", weight: 3, kind: "bonus", color: "#f0abfc" },
      { id: "coin", label: "Coin", icon: "ðŸª™", weight: 7, kind: "coin", color: "#fde047" },
    ],
    waysToWin: "8 canyon paylines",
    payoutTable: [
      { symbol: "eagle", count: 5, multiplier: 260 },
      { symbol: "bison", count: 5, multiplier: 185 },
      { symbol: "wolf", count: 4, multiplier: 62 },
      { symbol: "cougar", count: 4, multiplier: 38 },
      { symbol: "canyon", count: 3, multiplier: 10 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "coin",
    bonusFeature: { meterPerSpin: 9 },
    freeSpins: { triggerCount: 99, awarded: [0, 0], winMultiplier: 1, retrigger: false },
    pickBonus: { triggerCount: 99, picks: 0, awards: [] },
    demoProgressive: { seed: 150000, contributionRate: 0.006, maxPayoutMultiplier: 70 },
    visual: {
      accent: "#38bdf8",
      secondary: "#f97316",
      panel: "#32160d",
      logo: "FF",
      logoImage: "/assets/ui/frontier/title-logo.png",
      background: "frontier",
      cabinet: "canyon",
    },
  },
  {
    id: "martial-mansions",
    name: "Martial Mansions",
    theme: "Sunset dojo free spins",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 500,
    volatility: "Medium",
    targetRtp: 0.92,
    maxPayoutMultiplier: 55,
    jackpotLabels: { Grand: "500x", Major: "75x", Minor: "20x", Mini: "8x" },
    buyBonus: { enabled: true, costMultiplier: 70, featureType: "FREE_SPINS" },
    featureTypes: ["FREE_SPINS"],
    specialSymbols: { wild: "wild", scatter: "scatter", bonus: "dragon", multiplier: "dragon" },
    symbols: [
      { id: "dragon", label: "Dragon", icon: "DRG", weight: 7, color: "#f0abfc" },
      { id: "koi", label: "Koi", icon: "KOI", weight: 10, color: "#38bdf8" },
      { id: "scroll", label: "Scroll", icon: "SCR", weight: 13, color: "#f97316" },
      { id: "fan", label: "Fan", icon: "FAN", weight: 15, color: "#fb7185" },
      { id: "lantern", label: "Lantern", icon: "LAN", weight: 22, color: "#fde047" },
      { id: "katana", label: "Katana", icon: "KAT", weight: 18, color: "#67e8f9" },
      { id: "wild", label: "Wild", icon: "WILD", weight: 4, kind: "wild", color: "#a78bfa" },
      { id: "scatter", label: "Free Spins", icon: "FS", weight: 4, kind: "scatter", color: "#22d3ee" },
    ],
    waysToWin: "8 dojo paylines",
    payoutTable: [
      { symbol: "dragon", count: 5, multiplier: 225 },
      { symbol: "koi", count: 5, multiplier: 150 },
      { symbol: "scroll", count: 4, multiplier: 54 },
      { symbol: "fan", count: 4, multiplier: 32 },
      { symbol: "lantern", count: 3, multiplier: 9 },
      { symbol: "katana", count: 3, multiplier: 7 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "dragon",
    bonusFeature: { meterPerSpin: 7 },
    freeSpins: { triggerCount: 3, awarded: [7, 10], winMultiplier: 1.8, retrigger: true },
    pickBonus: { triggerCount: 99, picks: 0, awards: [] },
    demoProgressive: { seed: 90000, contributionRate: 0.005, maxPayoutMultiplier: 55 },
    visual: {
      accent: "#f0abfc",
      secondary: "#22d3ee",
      panel: "#2a1438",
      logo: "MM",
      background: "dojo",
      cabinet: "dojo",
    },
  },
  {
    id: "electric-millions",
    name: "Electric Millions",
    theme: "Neon wheel multiplier show",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 500,
    volatility: "High",
    targetRtp: 0.9,
    maxPayoutMultiplier: 80,
    jackpotLabels: { Grand: "750x", Major: "100x", Minor: "25x", Mini: "10x" },
    buyBonus: { enabled: true, costMultiplier: 90, featureType: "WHEEL_BONUS" },
    featureTypes: ["WHEEL_BONUS"],
    specialSymbols: { wild: "wild", bonus: "wheel", multiplier: "multiplier" },
    symbols: [
      { id: "diamond", label: "Diamond", icon: "DIA", weight: 8, color: "#fde047" },
      { id: "star", label: "Star", icon: "STR", weight: 11, color: "#38bdf8" },
      { id: "emerald", label: "Emerald", icon: "EMR", weight: 14, color: "#22c55e" },
      { id: "bolt", label: "Bolt", icon: "BLT", weight: 18, color: "#f0abfc" },
      { id: "card", label: "Card", icon: "A", weight: 22, color: "#fb7185" },
      { id: "wild", label: "Wild", icon: "WILD", weight: 4, kind: "wild", color: "#a78bfa" },
      { id: "wheel", label: "Wheel", icon: "WHL", weight: 5, kind: "bonus", color: "#67e8f9" },
      { id: "multiplier", label: "Multiplier", icon: "X", weight: 7, kind: "multiplier", color: "#f97316" },
    ],
    waysToWin: "8 neon paylines",
    payoutTable: [
      { symbol: "diamond", count: 5, multiplier: 300 },
      { symbol: "star", count: 5, multiplier: 170 },
      { symbol: "emerald", count: 4, multiplier: 58 },
      { symbol: "bolt", count: 4, multiplier: 34 },
      { symbol: "card", count: 3, multiplier: 9 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "wheel",
    bonusSymbol: "wheel",
    bonusFeature: { meterPerSpin: 10 },
    freeSpins: { triggerCount: 99, awarded: [0, 0], winMultiplier: 1, retrigger: false },
    pickBonus: { triggerCount: 99, picks: 0, awards: [] },
    demoProgressive: { seed: 200000, contributionRate: 0.006, maxPayoutMultiplier: 80 },
    visual: {
      accent: "#22d3ee",
      secondary: "#f0abfc",
      panel: "#101342",
      logo: "EX",
      background: "electric",
      cabinet: "stage",
    },
  },
  {
    id: "neon-fortune",
    name: "Neon Fortune",
    theme: "Cyber neon arcade",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 500,
    volatility: "Medium",
    targetRtp: 0.91,
    maxPayoutMultiplier: 40,
    symbols: [
      { id: "seven", label: "Seven", icon: "7", weight: 7, color: "#38bdf8" },
      { id: "bar", label: "BAR", icon: "â–°", weight: 11, color: "#a78bfa" },
      { id: "chip", label: "Chip", icon: "â—‰", weight: 16, color: "#22d3ee" },
      { id: "diamond", label: "Diamond", icon: "â—‡", weight: 18, color: "#60a5fa" },
      { id: "lightning", label: "Volt", icon: "ÏŸ", weight: 24, color: "#e879f9" },
      featureSymbols.wild,
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 neon paylines",
    payoutTable: [
      { symbol: "seven", count: 5, multiplier: 184 },
      { symbol: "bar", count: 5, multiplier: 107 },
      { symbol: "chip", count: 4, multiplier: 41 },
      { symbol: "diamond", count: 4, multiplier: 26 },
      { symbol: "lightning", count: 3, multiplier: 8.8 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 8 },
    freeSpins: { triggerCount: 3, awarded: [5, 8], winMultiplier: 1.7, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1.5, 2, 3, 4, 6, 9] },
    demoProgressive: { seed: 50000, contributionRate: 0.01, maxPayoutMultiplier: 40 },
    visual: { accent: "#22d3ee", secondary: "#c084fc", panel: "#12183a", logo: "âš¡" },
  },
  {
    id: "pirate-plunder",
    name: "Pirate Plunder",
    theme: "Midnight treasure raid",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 100,
    maxBet: 500,
    volatility: "High",
    targetRtp: 0.9,
    maxPayoutMultiplier: 55,
    symbols: [
      { id: "skull", label: "Skull", icon: "â˜ ", weight: 6, color: "#e0e7ff" },
      { id: "ship", label: "Ship", icon: "â›µ", weight: 10, color: "#38bdf8" },
      { id: "map", label: "Map", icon: "âŒ", weight: 16, color: "#c084fc" },
      { id: "chest", label: "Chest", icon: "â–£", weight: 18, color: "#f0abfc" },
      { id: "coin", label: "Coin", icon: "â—", weight: 25, color: "#facc15" },
      featureSymbols.wild,
      { ...featureSymbols.scatter, weight: 2 },
      { ...featureSymbols.bonus, weight: 4 },
    ],
    waysToWin: "8 treasure paylines",
    payoutTable: [
      { symbol: "skull", count: 5, multiplier: 360 },
      { symbol: "ship", count: 5, multiplier: 189 },
      { symbol: "map", count: 4, multiplier: 72 },
      { symbol: "chest", count: 4, multiplier: 41 },
      { symbol: "coin", count: 3, multiplier: 10.6 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 10 },
    freeSpins: { triggerCount: 3, awarded: [5, 7], winMultiplier: 1.5, retrigger: false },
    pickBonus: { triggerCount: 3, picks: 2, awards: [1, 1.5, 2, 3, 5, 8] },
    demoProgressive: { seed: 120000, contributionRate: 0.008, maxPayoutMultiplier: 55 },
    visual: { accent: "#38bdf8", secondary: "#7c3aed", panel: "#111a32", logo: "â˜ " },
  },
  {
    id: "cosmic-reels",
    name: "Cosmic Reels",
    theme: "Galaxy hyperspin",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 500,
    volatility: "Medium",
    targetRtp: 0.92,
    maxPayoutMultiplier: 45,
    symbols: [
      { id: "planet", label: "Planet", icon: "â—", weight: 8, color: "#818cf8" },
      { id: "rocket", label: "Rocket", icon: "â–²", weight: 12, color: "#22d3ee" },
      { id: "star", label: "Star", icon: "âœ¶", weight: 15, color: "#c084fc" },
      { id: "moon", label: "Moon", icon: "â˜¾", weight: 19, color: "#93c5fd" },
      { id: "alien", label: "Alien", icon: "âŒ¬", weight: 24, color: "#2dd4bf" },
      featureSymbols.wild,
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 orbital paylines",
    payoutTable: [
      { symbol: "planet", count: 5, multiplier: 302 },
      { symbol: "rocket", count: 5, multiplier: 163 },
      { symbol: "star", count: 4, multiplier: 65 },
      { symbol: "moon", count: 4, multiplier: 40 },
      { symbol: "alien", count: 3, multiplier: 13.2 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 9 },
    freeSpins: { triggerCount: 3, awarded: [6, 10], winMultiplier: 1.8, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1.5, 2, 3, 4, 6, 10] },
    demoProgressive: { seed: 80000, contributionRate: 0.009, maxPayoutMultiplier: 45 },
    visual: { accent: "#a78bfa", secondary: "#22d3ee", panel: "#1e1b4b", logo: "â—" },
  },
  {
    id: "jungle-jackpot",
    name: "Jungle Jackpot",
    theme: "Tiki temple chase",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 25,
    maxBet: 500,
    volatility: "Low",
    targetRtp: 0.93,
    maxPayoutMultiplier: 24,
    symbols: [
      { id: "tiger", label: "Tiger", icon: "â—†", weight: 9, color: "#34d399" },
      { id: "leaf", label: "Leaf", icon: "â§", weight: 14, color: "#2dd4bf" },
      { id: "tiki", label: "Tiki", icon: "â–¥", weight: 17, color: "#a78bfa" },
      { id: "banana", label: "Banana", icon: "â—’", weight: 22, color: "#fde047" },
      { id: "gem", label: "Gem", icon: "â—‡", weight: 25, color: "#38bdf8" },
      { ...featureSymbols.wild, weight: 4 },
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 jungle paylines",
    payoutTable: [
      { symbol: "tiger", count: 5, multiplier: 277 },
      { symbol: "leaf", count: 5, multiplier: 170 },
      { symbol: "tiki", count: 4, multiplier: 65 },
      { symbol: "banana", count: 4, multiplier: 41 },
      { symbol: "gem", count: 3, multiplier: 14.8 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 6 },
    freeSpins: { triggerCount: 3, awarded: [5, 8], winMultiplier: 1.35, retrigger: false },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1, 1.5, 2, 3, 4, 6] },
    demoProgressive: { seed: 30000, contributionRate: 0.006, maxPayoutMultiplier: 24 },
    visual: { accent: "#2dd4bf", secondary: "#8b5cf6", panel: "#052e2b", logo: "â—†" },
  },
  {
    id: "candy-rush",
    name: "Candy Rush",
    theme: "Sugar pop reels",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 25,
    maxBet: 500,
    volatility: "Low",
    targetRtp: 0.89,
    maxPayoutMultiplier: 20,
    symbols: [
      { id: "lollipop", label: "Lollipop", icon: "â—", weight: 10, color: "#fb7185" },
      { id: "gummy", label: "Gummy", icon: "â¬¡", weight: 15, color: "#22d3ee" },
      { id: "donut", label: "Donut", icon: "â—Ž", weight: 18, color: "#c084fc" },
      { id: "cupcake", label: "Cupcake", icon: "â™¢", weight: 23, color: "#f0abfc" },
      { id: "candy", label: "Candy", icon: "â—", weight: 26, color: "#67e8f9" },
      { ...featureSymbols.wild, weight: 4 },
      { ...featureSymbols.scatter, weight: 4 },
      featureSymbols.bonus,
    ],
    waysToWin: "8 candy paylines",
    payoutTable: [
      { symbol: "lollipop", count: 5, multiplier: 271 },
      { symbol: "gummy", count: 5, multiplier: 175 },
      { symbol: "donut", count: 4, multiplier: 67 },
      { symbol: "cupcake", count: 4, multiplier: 42 },
      { symbol: "candy", count: 3, multiplier: 15 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 5 },
    freeSpins: { triggerCount: 3, awarded: [5, 7], winMultiplier: 1.45, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1, 1.5, 2, 3, 4, 5] },
    demoProgressive: { seed: 25000, contributionRate: 0.005, maxPayoutMultiplier: 20 },
    visual: { accent: "#fb5bd6", secondary: "#22d3ee", panel: "#3b0a55", logo: "â—Ž" },
  },
];

export const exposedSlotConfigs = slotConfigs.filter((game) => game.id === "frontier-fortune");

export function getSlotConfig(gameId: string) {
  return slotConfigs.find((game) => game.id === gameId) ?? exposedSlotConfigs[0];
}
