import { standardPaylines } from "./paylines";
import type { SlotConfig } from "./types";

const featureSymbols = {
  wild: { id: "wild", label: "WILD", icon: "✦", weight: 3, kind: "wild" as const, color: "#67e8f9" },
  scatter: { id: "scatter", label: "SCATTER", icon: "◆", weight: 3, kind: "scatter" as const, color: "#c084fc" },
  bonus: { id: "bonus", label: "BONUS", icon: "★", weight: 3, kind: "bonus" as const, color: "#f0abfc" },
};

export const slotConfigs: SlotConfig[] = [
  {
    id: "neon-fortune",
    name: "Neon Fortune",
    theme: "Cyber neon arcade",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 2500,
    volatility: "Medium",
    targetRtp: 0.91,
    maxPayoutMultiplier: 40,
    symbols: [
      { id: "seven", label: "Seven", icon: "7", weight: 7, color: "#38bdf8" },
      { id: "bar", label: "BAR", icon: "▰", weight: 11, color: "#a78bfa" },
      { id: "chip", label: "Chip", icon: "◉", weight: 16, color: "#22d3ee" },
      { id: "diamond", label: "Diamond", icon: "◇", weight: 18, color: "#60a5fa" },
      { id: "lightning", label: "Volt", icon: "ϟ", weight: 24, color: "#e879f9" },
      featureSymbols.wild,
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 neon paylines",
    payoutTable: [
      { symbol: "seven", count: 5, multiplier: 184 },
      { symbol: "bar", count: 5, multiplier: 107 },
      { symbol: "chip", count: 4, multiplier: 41 },
      { symbol: "diamond", count: 4, multiplier: 26 },
      { symbol: "lightning", count: 3, multiplier: 8.8 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 8 },
    freeSpins: { triggerCount: 3, awarded: [5, 8], winMultiplier: 1.7, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1.5, 2, 3, 4, 6, 9] },
    demoProgressive: { seed: 50000, contributionRate: 0.01, maxPayoutMultiplier: 40 },
    visual: { accent: "#22d3ee", secondary: "#c084fc", panel: "#12183a", logo: "⚡" },
  },
  {
    id: "pirate-plunder",
    name: "Pirate Plunder",
    theme: "Midnight treasure raid",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 100,
    maxBet: 5000,
    volatility: "High",
    targetRtp: 0.9,
    maxPayoutMultiplier: 55,
    symbols: [
      { id: "skull", label: "Skull", icon: "☠", weight: 6, color: "#e0e7ff" },
      { id: "ship", label: "Ship", icon: "⛵", weight: 10, color: "#38bdf8" },
      { id: "map", label: "Map", icon: "⌁", weight: 16, color: "#c084fc" },
      { id: "chest", label: "Chest", icon: "▣", weight: 18, color: "#f0abfc" },
      { id: "coin", label: "Coin", icon: "●", weight: 25, color: "#facc15" },
      featureSymbols.wild,
      { ...featureSymbols.scatter, weight: 2 },
      { ...featureSymbols.bonus, weight: 4 },
    ],
    waysToWin: "8 treasure paylines",
    payoutTable: [
      { symbol: "skull", count: 5, multiplier: 360 },
      { symbol: "ship", count: 5, multiplier: 189 },
      { symbol: "map", count: 4, multiplier: 72 },
      { symbol: "chest", count: 4, multiplier: 41 },
      { symbol: "coin", count: 3, multiplier: 10.6 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 10 },
    freeSpins: { triggerCount: 3, awarded: [5, 7], winMultiplier: 1.5, retrigger: false },
    pickBonus: { triggerCount: 3, picks: 2, awards: [1, 1.5, 2, 3, 5, 8] },
    demoProgressive: { seed: 120000, contributionRate: 0.008, maxPayoutMultiplier: 55 },
    visual: { accent: "#38bdf8", secondary: "#7c3aed", panel: "#111a32", logo: "☠" },
  },
  {
    id: "cosmic-reels",
    name: "Cosmic Reels",
    theme: "Galaxy hyperspin",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 50,
    maxBet: 3000,
    volatility: "Medium",
    targetRtp: 0.92,
    maxPayoutMultiplier: 45,
    symbols: [
      { id: "planet", label: "Planet", icon: "◐", weight: 8, color: "#818cf8" },
      { id: "rocket", label: "Rocket", icon: "▲", weight: 12, color: "#22d3ee" },
      { id: "star", label: "Star", icon: "✶", weight: 15, color: "#c084fc" },
      { id: "moon", label: "Moon", icon: "☾", weight: 19, color: "#93c5fd" },
      { id: "alien", label: "Alien", icon: "⌬", weight: 24, color: "#2dd4bf" },
      featureSymbols.wild,
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 orbital paylines",
    payoutTable: [
      { symbol: "planet", count: 5, multiplier: 302 },
      { symbol: "rocket", count: 5, multiplier: 163 },
      { symbol: "star", count: 4, multiplier: 65 },
      { symbol: "moon", count: 4, multiplier: 40 },
      { symbol: "alien", count: 3, multiplier: 13.2 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 9 },
    freeSpins: { triggerCount: 3, awarded: [6, 10], winMultiplier: 1.8, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1.5, 2, 3, 4, 6, 10] },
    demoProgressive: { seed: 80000, contributionRate: 0.009, maxPayoutMultiplier: 45 },
    visual: { accent: "#a78bfa", secondary: "#22d3ee", panel: "#1e1b4b", logo: "◐" },
  },
  {
    id: "jungle-jackpot",
    name: "Jungle Jackpot",
    theme: "Tiki temple chase",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 25,
    maxBet: 2000,
    volatility: "Low",
    targetRtp: 0.93,
    maxPayoutMultiplier: 24,
    symbols: [
      { id: "tiger", label: "Tiger", icon: "◆", weight: 9, color: "#34d399" },
      { id: "leaf", label: "Leaf", icon: "❧", weight: 14, color: "#2dd4bf" },
      { id: "tiki", label: "Tiki", icon: "▥", weight: 17, color: "#a78bfa" },
      { id: "banana", label: "Banana", icon: "◒", weight: 22, color: "#fde047" },
      { id: "gem", label: "Gem", icon: "◇", weight: 25, color: "#38bdf8" },
      { ...featureSymbols.wild, weight: 4 },
      featureSymbols.scatter,
      featureSymbols.bonus,
    ],
    waysToWin: "8 jungle paylines",
    payoutTable: [
      { symbol: "tiger", count: 5, multiplier: 277 },
      { symbol: "leaf", count: 5, multiplier: 170 },
      { symbol: "tiki", count: 4, multiplier: 65 },
      { symbol: "banana", count: 4, multiplier: 41 },
      { symbol: "gem", count: 3, multiplier: 14.8 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 6 },
    freeSpins: { triggerCount: 3, awarded: [5, 8], winMultiplier: 1.35, retrigger: false },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1, 1.5, 2, 3, 4, 6] },
    demoProgressive: { seed: 30000, contributionRate: 0.006, maxPayoutMultiplier: 24 },
    visual: { accent: "#2dd4bf", secondary: "#8b5cf6", panel: "#052e2b", logo: "◆" },
  },
  {
    id: "candy-rush",
    name: "Candy Rush",
    theme: "Sugar pop reels",
    reelCount: 5,
    rowCount: 3,
    paylines: standardPaylines,
    minBet: 25,
    maxBet: 1500,
    volatility: "Low",
    targetRtp: 0.89,
    maxPayoutMultiplier: 20,
    symbols: [
      { id: "lollipop", label: "Lollipop", icon: "◍", weight: 10, color: "#fb7185" },
      { id: "gummy", label: "Gummy", icon: "⬡", weight: 15, color: "#22d3ee" },
      { id: "donut", label: "Donut", icon: "◎", weight: 18, color: "#c084fc" },
      { id: "cupcake", label: "Cupcake", icon: "♢", weight: 23, color: "#f0abfc" },
      { id: "candy", label: "Candy", icon: "●", weight: 26, color: "#67e8f9" },
      { ...featureSymbols.wild, weight: 4 },
      { ...featureSymbols.scatter, weight: 4 },
      featureSymbols.bonus,
    ],
    waysToWin: "8 candy paylines",
    payoutTable: [
      { symbol: "lollipop", count: 5, multiplier: 271 },
      { symbol: "gummy", count: 5, multiplier: 175 },
      { symbol: "donut", count: 4, multiplier: 67 },
      { symbol: "cupcake", count: 4, multiplier: 42 },
      { symbol: "candy", count: 3, multiplier: 15 },
    ],
    twoMatchMultiplier: 0,
    scatterSymbol: "scatter",
    bonusSymbol: "bonus",
    bonusFeature: { meterPerSpin: 5 },
    freeSpins: { triggerCount: 3, awarded: [5, 7], winMultiplier: 1.45, retrigger: true },
    pickBonus: { triggerCount: 3, picks: 1, awards: [1, 1.5, 2, 3, 4, 5] },
    demoProgressive: { seed: 25000, contributionRate: 0.005, maxPayoutMultiplier: 20 },
    visual: { accent: "#fb5bd6", secondary: "#22d3ee", panel: "#3b0a55", logo: "◎" },
  },
];

export function getSlotConfig(gameId: string) {
  return slotConfigs.find((game) => game.id === gameId) ?? slotConfigs[0];
}
